<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="AutoMapper" Version="13.0.1" />
      <PackageReference Include="Dapper" Version="2.0.123" />
      <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.5.0" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.0-rc.2.24473.5" />
      <PackageReference Include="Npgsql" Version="8.0.5" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Padel.Domain\Padel.Domain.csproj" />
      <ProjectReference Include="..\Padel.Infrastructure\Padel.Infrastructure.csproj" />
    </ItemGroup>

</Project>
